# Generated by Django 5.0.4 on 2024-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name_plural': '1. Chef'},
        ),
        migrations.AlterModelOptions(
            name='chefrecipe',
            options={'verbose_name_plural': '3. Chef Recipe'},
        ),
        migrations.AlterModelOptions(
            name='chefrecipecategory',
            options={'verbose_name_plural': '2. Chef Recipe Categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '4. User'},
        ),
        migrations.AlterField(
            model_name='chef',
            name='address',
            field=models.TextField(),
        ),
    ]
