# Generated by Django 5.0.4 on 2024-04-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0002_alter_chef_options_alter_chefrecipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='address',
            new_name='skills',
        ),
    ]
