# Generated by Django 5.0.4 on 2024-04-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0003_rename_address_chef_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='skills',
            new_name='address',
        ),
    ]
