# Generated by Django 5.0.4 on 2024-04-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0005_remove_chefrecipe_dish_type_chefrecipe_featured_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefrecipe',
            name='category',
        ),
    ]
