# Generated by Django 5.0.4 on 2024-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0008_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='chef_profile_imgs/'),
        ),
    ]
