# Generated by Django 5.0.4 on 2024-05-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0011_userfavoriterecipe_userrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
