# Generated by Django 5.0.4 on 2024-05-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0013_userrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecipe',
            options={'verbose_name_plural': 'User Recipes'},
        ),
        migrations.DeleteModel(
            name='UserFavoriteRecipe',
        ),
    ]
