# Generated by Django 5.0.4 on 2024-05-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0014_alter_userrecipe_options_delete_userfavoriterecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecipe',
            options={'verbose_name_plural': '4.User Recipes'},
        ),
    ]
