# Generated by Django 5.0.4 on 2024-05-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0017_rename_usrrecipe_userrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
