# Generated by Django 5.0.4 on 2024-05-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0019_userrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.chefrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.user')),
            ],
            options={
                'verbose_name_plural': '4.User Favorite Recipes',
            },
        ),
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
