# Generated by Django 5.0.4 on 2024-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefrecipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
