# Generated by Django 5.0.4 on 2024-05-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0025_rename_userfavoriterecipe_usercheffavoriterecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercheffavoriterecipe',
            options={'verbose_name_plural': '4.User Chef Favorite Recipes'},
        )
    ]
