# Generated by Django 5.0.4 on 2024-05-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0026_alter_usercheffavoriterecipe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteRecipeAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('urecipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frapp.userrecipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frapp.user')),
            ],
            options={
                'verbose_name_plural': '6.User Favorite Recipes',
            },
        ),
    ]
