# Generated by Django 5.0.4 on 2024-05-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0027_userfavoriterecipeadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoriterecipeadd',
            old_name='urecipe',
            new_name='recipe',
        ),
    ]
