# Generated by Django 5.0.4 on 2024-05-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0028_rename_urecipe_userfavoriterecipeadd_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefFavoriteRecipeAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.chef')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frapp.chefrecipe')),
            ],
            options={
                'verbose_name_plural': '4.Chef Favorite Recipes',
            },
        ),
    ]
