# Generated by Django 5.0.4 on 2024-05-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0029_cheffavoriterecipeadd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheffavoriterecipeadd',
            options={'verbose_name_plural': '7.Chef Favorite Recipes'},
        ),
        migrations.CreateModel(
            name='ChefUserFavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frapp.chef')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frapp.userrecipe')),
            ],
            options={
                'verbose_name_plural': '8. Chef User Favorite Recipes',
            },
        ),
    ]
